### ISSUE TITLE
Yes/No prompt for BAN doesn't work as intended.

### ISSUE THREAD

**Issue by weylin** [r-DestinyTheGame/Sweeper-Bot#137] opened 2017-09-24 23:04 UTC
Even though the full string for `yes` and `no` are in the REGEX the bot seems to simply ignore a `yes` in favor of a `y` only.

https://github.com/r-DestinyTheGame/Sweeper-Bot/blob/0fd1e8c1040d82be2341777ac9c9e07c20564558/src/commands/modtools/Ban.ts#L124-L126

**Comment by D0cR3d** [comment] 2017-09-25 04:02
Tested this, unable to reproduce both in dev and in prod. It took both 'no', 'n', 'yes', and 'y'.

**Comment by weylin** [comment] 2017-09-25 13:02
Maybe I ran into some type of discord delay? This morning when I look back at the messages the order is now different.

**Comment by D0cR3d** [comment] 2017-09-26 03:24
Closing as unable to duplicate.

**Closed by D0cR3d** 2017-09-26 03:24 UTC
